from naukma import NaUKMA
from system import System
from faculty import Faculty
from cathedra import Cathedra
from discipline import Discipline
from specialty import Specialty
from person import Person
from student import Student
from teacher import Teacher
